apiVersion: v1
kind: Service
metadata:
  name: bayechat-client-service
  labels:
    app: bayeChat
    type: client-service
spec:
  type: NodePort
  ports:
    - targetPort: 5173
      port: 5173
      nodePort: 30001
  selector: 
    app: bayeChat
    type: front-end-pod