apiVersion: v1
kind: Service
metadata: 
  name: bayechat-test-server-service
  labels:
    app: bayeChat
    type: server-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5700
      port: 5800
  selector:
    app: bayeChat
    type: server-pod