apiVersion: v1
kind: Service
metadata: 
  name: bayechat-server-service
  labels:
    app: bayeChat
    type: server-service
spec:
  type: NodePort
  ports:
    - targetPort: 5700
      port: 5700
      nodePort: 30003
  selector:
    app: bayeChat
    type: server-pod